FROM node:20.3.0
WORKDIR /next_project
RUN npm install -g next
COPY ./next_project/package.json ./next_project/package-lock.json ./
RUN npm ci
COPY ./next_project .
RUN npm run build
EXPOSE 3000
CMD ["npm", "run", "dev"]
